name: deploy library
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Prepare maven
        uses: actions/setup-java@v5
        with:
          java-version: 26
          distribution: temurin
      - uses: s4u/maven-settings-action@v4.0.0
      - name: Run maven
        run: mvn clean deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/woldsom/Common
